### ISSUE TITLE
Hardware Code of Attention Processor

### ISSUE THREAD

**Issue by ZhangYuanQing99** [SamsungLabs/Butterfly_Acc#6]
Hi, I have been reviewing your code and found it highly insightful. However, I noticed that the implementation seems to only include the Butterfly Processor from the hardware architecture diagram presented in the paper. Could you kindly clarify if the Attention Processor has been implemented in the current codebase? If not, is there any plan to release its implementation, or any guidance on how one could proceed to implement it?

Thank you for your time and contributions.

**Comment by os-hxfan** [comment]
Thanks for your interest.
1. During the design space exploration in our experiments (Section-V and Section-VI), our co-design framework suggests that the Attention Processor should be optimized away (This is included in our experiment, pls read ). This means the Butterfly-only Processor can achieve the best algorithmic & hardware performance in our target tasks. Therefore, in our final hardware design, we used the Butterfly-only Processor to achieve the **best performance**.
2. You can still check the performance of the Attention Processor using the simulator we provided. That simulator is cross-checked with our RTL design of Attention Processor and waveform simulation. Although the hardware design of the Attention processor is not used in our experiments, we might consider open-sourcing the RTL design in another paper as a baseline in the future.
